### ISSUE TITLE
Conceptually separate execution from context

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#115]
The concept of a "context" now means two things in TESTed:

- a single execution of a list of tests
- a group of dependent tests

I would like to suggest to separate this in two concepts. The former could be called an "execution" and the latter a "context" (*sensu strictu*).

The reason we want to bundle multiple testcases in a single **execution** is merely **performance**. For example, we want to define a function once (as provided in the submitted code) but call it multiple times to test it with different arguments. Logically, however, all these function calls are independent of each other (and so they could also be tested in separate executions, with a performance penalty). Bundling the function calls in the same execution also gives the opportunity to let things like *memoization* do their job (again a performance issue).

The reason we want to bundle multiple testcases in a single **context** is because **they depend on each other**. For example, one testcase might assign a value to a variable, that is used in a downstream testcase. If one testcase fails, there's no reason to continue testing its downstream testcases.

There's no need to bring "executions" to the feedback table. For a user, it's not relevant whether the context are in separate executions or in a single execution. Only the "contexts" are relavent in the feedback table (logically group dependent testcases).

The current behaviour of TESTed, where execution and context are one and the same thing could be the default behaviour. In addition, we could add two ways to split the execution in multiple contexts:

- add an execution-level setting that indicates that all testcases in the execution are independent; as a result all testcases should go into their own context
- add a testcase-level setting that marks the testcase as the start of a new context; the first testcase of an execution implicitly starts a new context

**Comment by bsels** [comment]
I think it's more logical to add an execution-level setting at in the context, that indicates if the context must be forced to be started in a new executable. We have also an implicit execution seperations when defining an input-output context testcase.

This is a requirement because not all languages support to execute the main call multiple times in one executable.
Java support this, Python doesn't.

Suggestions for this optionname are welcome, one name I think we can use is `force_execution_break`

**Comment by niknetniko** [comment]
(I use run in this text to describe one execution of an executable, as is currently done for each context)

I would suggest making a "run" a new, mandatory level in the testplan. The hierarchy is then tab -> run -> context -> testcase -> test. If you want to have the old behaviour of each context in a separate "execution", you should put each in a different run.

My reasons include:

1. The philosophy of the json testplan has always been to be as explicit as possible. We don't allow omitting anything. Allowing "implicit" runs would break with this, and make the code in the judge for "parsing" the testplan more complex.
2. Making a run a "proper" level allows us to do some optimisations in the implementation: we could generate one executable per run, which contains multiple functions internally mapping to each context. While it does not prevent setting and accessing static or global variables, it does enforce some separation (since testcases are all generated within the same function). Always having a run would also make the implementation a less complex than having optional runs.

I'm still thinking how we would integrate multiple tabs in one run into this, without resorting to optional or multiple hierarchies. (Since a tab is currently used to parallelize the executions). It's perhaps an idea to focus on contexts in runs first, and then see if multiple tabs in one run is worth the additional complexity.

**Comment by pdawyndt** [comment]
I agree to have a fixed tab - run - context - testcase hierarchy. The only real case that is not covered by this, I think, is to have "all contexts of all tabs in one run" (I don't see a case to group specific tabs in one run). Let's first see if we ever need the "all tabs in one run" case, and if so, we could later also resort to use a flag for this (which seems a better alternative than combining two hierarchies).
