### ISSUE TITLE
Better representation of unexpected exception

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#121]
If an exception was raised, but no exception was expected, it would be better to only show the error message. The comparison of the exception message to an empty string has no additional value and so only clutters the feedback table.

How it looks now:

![image](https://user-images.githubusercontent.com/5736113/101469788-7433a380-3945-11eb-89e9-0ce7aeaafc84.png)

How it would look if suggested:

![image](https://user-images.githubusercontent.com/5736113/101470061-cc6aa580-3945-11eb-8697-d8a084f52aec.png)
Example: [submission 6678183](https://dodona.ugent.be/en/submissions/6678183/)

**Comment by bsels** [comment]
Good suggestion, but according to the JSON scheme of the partion output of a judge of Dodona, it'sn't possible because of the required [expected](https://github.com/dodona-edu/dodona/blob/c955b280808e689e5185b19706c9610127581ea1/public/schemas/partial_output.json#L61) and [actual](https://github.com/dodona-edu/dodona/blob/c955b280808e689e5185b19706c9610127581ea1/public/schemas/partial_output.json#L104) value.

**Comment by pdawyndt** [comment]
@ninewise Can this requirement be relaxed? I guess it isn't required in the full JSON scheme?

**Comment by niknetniko** [comment]
As an update, this is how it currently looks:

![image](https://github.com/dodona-edu/universal-judge/assets/1756811/9737ca15-a7b2-41d4-9450-9926fee166a8)

The duplication is still present, and I don't currently see a good way to get rid of it.
