### ISSUE TITLE
Internal datatypes

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#158]
**Problem:** Two different datatypes of TESTed are mapped on the same datatype in a programming languages. When that datatype is returned only one datatype from TESTed could be provide.

**Consequence:** Possible mismatch with datatype expected by the TESTed value evaluator.
**Some examples:**
1) `Java`/`Kotlin`:

| TESTed type1 | TESTed type 2 | Java/Kotlin type |
| --- | --- | --- |
| uint8 | int16 | short |
| uint16 | int32 | int |
| uint32 | int64 | long |
| uint64 | bigint | BigInteger |
| double_extended | fixed_precision | BigDecimal |

2) `Python`/`JavaScript`: no datatype for individual characters, both uses the datatype for strings.

**Possible solution:**
Possibility to provide more then one datatype from TESTed when passing a data value to TESTed from the evaluation code.
**Only** for datatypes from TESTed that mapped to the same datatype in the programming language.

**Example solution:**
1) Numbers Java/Kotlin:
```json
{
    "data": 255,
    "type": ["uint8", "int16"]
}
```
```json
{
    "data": 256,
    "type": "int16"
}
```

2) Characters and String Python/JavaScript:
```json
{
    "data": "a",
    "type": ["char", "text"]
}
```
```json
{
    "data": "ab",
    "type": "text"
}
```

**Comment by bsels** [comment]
An example of a failing example in Java and Kotlin:
```yaml
- tab: "Feedback"
  contexts:
    - expression: '5 :: uint8'
      return-raw: '5 :: uint8'
```

Feedback result Java:
```json
{"description": {"description": "(short) 5", "format": "java"}, "command": "start-testcase"}
{"expected": "(short) 5", "channel": "return", "command": "start-test"}
{"message": "Verwachtte waarde van type AdvancedNumericTypes.U_INT_8, maar was type AdvancedNumericTypes.INT_16.", "command": "append-message"}
{"generated": "(short) 5", "status": {"enum": "wrong", "human": "Returnwaarde heeft verkeerd gegevenstype."}, "command": "close-test"}
{"command": "close-testcase"}
```

**Comment by niknetniko** [comment]
The indented logic for type comparisons

> Check if the type of the two values match. The following procedure is used:
> 1. If the expected value's type is a basic type, the actual value is reduced to it's basic type, after which both types are checked for equality.
> 2. If the expected value's type is an advanced type, there are two possibilities:
>    a. If the language of the submission supports the advanced type, both types are checked for equality.
>    b. If the language of the submission only supports a reduction of the type, all types are reduced to their basic type, after which equality is checked.
> 3. An error occurs if the language explicitly does not support the advanced type.

I think this system allows us to solve the raised issues by fixing the configs of the types:

1. The `uint*` types are currently listed as `supported` in Java; however I think they should be `reduced`, since there isn't really an `uint8` type. In the example, the returned type would be `int16`, but the expected type `uint8` is not fully supported in Java, so it would reduce both to `integer`, and compare those.
2. If we want to support using strings as char (e.g. in Python), we should move the `char` type to the advanced types, and define it as a specialized type of the basic type `text`.



I'm not against changing how this works, but I'm not convinced listing all possible advanced types is the best solution from the perspective we want to have as little as possible language specific stuff in the testplan. While the advanced types are not language specific, their inclusion is.

For example, this would work until we add a Java/Kotlin exercise, which is something we want to avoid.

```json
{
    "data": 256,
    "type": "int16"
}
```

**Comment by bsels** [comment]
> I'm not against changing how this works, but I'm not convinced listing all possible advanced types is the best solution from the perspective we want to have as little as possible language specific stuff in the testplan. While the advanced types are not language specific, their inclusion is.

It's not adding this functionality to the testplan, it's adding a custom (de)serialization format for internal usage in the judge.

**Comment by niknetniko** [comment]
> It's not adding this functionality to the testplan, it's adding a custom (de)serialization format for internal usage in the judge.

So this would only be added when generating json-values in the generated code (e.g. generated Java-code -> judge)?

If so, it could be a good solution, but I'm not entirely convinced the extra complexity has advantages against falling back on the basic types for advanced types that don't have a one-on-one mapping.

**Comment by bsels** [comment]
> So this would only be added when generating json-values in the generated code (e.g. generated Java-code -> judge)?

Indeed this would only be added when generating json-values in the generated code.
