### ISSUE TITLE
Klint is too strict

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/universal-judge#188]
Code style issues are categorized as error:

![image](https://user-images.githubusercontent.com/1756811/113169665-1e616f00-9246-11eb-9679-f81b4d9f4722.png)

https://dodona.ugent.be/en/submissions/7443019/

(also, it seems broken at the moment, https://dodona.ugent.be/en/submissions/7444992/, but unsure if related)

**Comment by bsels** [comment]
Broken Kotlin see #117, more examples: https://dodona.ugent.be/nl/submissions/7444988/ and https://dodona.ugent.be/en/submissions/7444992/.

**Comment by bsels** [comment]
KTLint has no severity level.
2 Suggestions:
1) Change severity level of all linter messages to `Severity.INFO`.
2) Depend severity level of a message depending on it's rule id.

I prefer to first suggestions because most rules (if not all) are code style issues, (see [KTLint rules](https://github.com/pinterest/ktlint#standard-rules)).
