### ISSUE TITLE
Add function chaining

### ISSUE THREAD

**Issue by bsels** [dodona-edu/universal-judge#229]
Add function chaining for OOP languages.
- [x] Enable function chaining in the JSON testplans
- [x] Enable function chaining in the DSL testplans
- [x] Write tests

**Comment by bsels** [comment]
I don't think this add much complexity:
The only thing that changes is the namespace and some validator tests and adding a construct `chained_functions`.
From `namespace: Optional[str] = None` to `namespace: Optional[Expression] = None`

**Comment by pdawyndt** [comment]
Rationale from my perspective. Method chaining used frequently in class exercises as a way to reduce complexity. Sometimes there's no need to test intermediate results because 

- methods have already been tested heavily in previous tests and chaining reduces "clutter" in the feedback table as it avoids sequential method calls in separate statements
- methods only change internal state of the object on which they are called and return the object itself so testing needs to be done in succession (e.g. converting the object to string and test that result)

Not supporting method chaining would only leave the option to have a more verbose feedback table: split chain into sequence of  separate statement, possibly needing to store intermediate results in temporary variables.
