### ISSUE TITLE
Report compilation error upon invalid JavaScript code

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/universal-judge#354]
Example: [submission 13892016](https://dodona.ugent.be/nl/submissions/13892016/#code)

Comment by @niknetniko:

> Het probleem zit op de lijnen 52-53: daar worden "octal literals" gebruikt, maar die zijn niet toegestaan in "strict mode", en alle code in een klasse is per definitie in "strict mode". De reden dat de oefeningen niet de status "compilatiefout" heeft, is waarschijnlijk een bug in TESTed.
> 
> De foutboodschap die verschijnt is omdat we in JavaScript, voor we de oplossing beoordelen, de AST parsen om alle functies en klassen te exporteren uit de oplossing (zodat we later "import ..." kunnen doen). Het parsen van de AST loopt echter fout (want het is geen geldige syntaxis), en dus zijn er geen exports, en dus krijg je "ReferenceError: Qlocktwo is not defined".
> 
> Ik kijk na waarom de compilatiefout niet doorgegeven wordt.

**Comment by niknetniko** [comment]
It seems like Node (and Chrome) don't enforce strict mode in this case, even though they should.
For example, the following code violates strict mode:

```javascript
class Example {
    static test = {
        00: '',
        05: 'VIJF NA',
        10: 'TIEN NA'
    };
}
```

However, both `node --check` and the Chrome console accept it without issue:
![image](https://user-images.githubusercontent.com/1756811/235150080-1e43fbcb-949c-471b-b1d7-d14344c9dd39.png)

However, [most libraries](https://astexplorer.net/#/gist/15e78a7134283b982741c967fc685dca/490a75a1c8a49d8d47702bc5c8f1b1028c8cb915) do not accept it, and neither does Firefox:
![image](https://user-images.githubusercontent.com/1756811/235150338-7f74302b-e213-4844-b39f-9254c4502457.png)

Some solutions could be:

- Enable strict mode everywhere.
- Use an alternative to `node --check` that does check it
- Somehow propagate errors from a later step inside TESTed

That last one is annoying, since that step shouldn't fail (so if it does, it should be an internal error instead).

**Comment by niknetniko** [comment]
Enabling strict mode everywhere is not as simple as it looks, since NodeJS apparently doesn't honour the `--use-strict` flag (see https://github.com/nodejs/node/issues/30039). It also became clear that the NodeJS people aren't a big fan of the flag.

A more robust way to enforce strict mode would then be to  add  `"use strict"` to every submission, but that is more work, although we do have support for this kind of thing.

A check of all the latest submissions from "Scriptingtalen" didn't reveal any instance where enabling strict mode changed the result.

**Comment by pdawyndt** [comment]
FYI: Here's an example of a [submission](https://dodona.ugent.be/nl/feedbacks/1889721965/) where the student enabled strict mode himself.
